
# --- HOW TO docker compose ------
# 1) $ docker compose up
# 2) Ctrl+c when ready to quit, shutdown can take about 15 seconds.
# 3) $ docker compose down
# --- NOTES ----------------------
# The `../../app.py:/app.py` volume is crucial to create an ADMIN role user,
# in the event that one does not exist (first boot, and accidental deletion).

version: "3.8"

services:
  cindi:
    image: ultasun/cindi-lite
    ports:
      - 36963:36963
    working_dir: /app
    volumes:
      - cindi-sqlite3-data:/app/data
      - cindi-logs:/app/logs
      - ./config:/app/config
      - ../../app-sqlite3.sql:/app/init-nonsense-sqlite3.sql
      - ../../app.py:/app/app.py

  raindb:
    image: ultasun/raindb-react
    ports:
      - 80:8080
    depends_on:
      - "cindi"
    working_dir: /app
    volumes:
      - ../../cindi-env.js:/app/cindi-env.js
volumes:
  cindi-sqlite3-data:
  cindi-logs:
  
  
